defaults:
    - agent: sac

env: platoon_exp

# "shared" or "individual"
multi_agent_mode: individual
equalize_agents: true

# "unilateral" or "bilateral"
control_mode: bilateral

# "train" or "eval"
mode: train
render: false

load_checkpoint: false
save_checkpoint: false
checkpoint_frequency: 1000

run_directory: 2024-02-24/11-17
checkpoint: cp_1011

num_train_steps: 6000
replay_buffer_capacity: 50000 #${num_train_steps}

num_seed_steps: 600

eval_frequency: 1000
num_eval_episodes: 6

fed_enabled: true
fed_and_update: true
fed_actor: true
fed_critic: true
fed_target: true
fed_alpha: true
fed_frequency: 1
fed_pre_weight: 0.33
fed_post_weight: 0.33
fed_first_post_weight: 0.33
fed_last_pre_weight: 0.33


# "cuda" or "cpu"
device: cuda

# logger
log_frequency: 600
log_save_tb: true

overall_seed: 1
initial_seed: 1


# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp
