defaults:
    - agent: sac

env: platoon_exp

# "shared" or "individual"
multi_agent_mode: shared 

# "train" or "eval"
mode: eval
render: true

load_checkpoint: true
save_checkpoint: true

run_directory: 2024-01-04/18-54
checkpoint: cp_12068

num_train_steps: 12000
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 3600

eval_frequency: 100000
num_eval_episodes: 1

# "cuda" or "cpu"
device: cpu

# logger
log_frequency: 600
log_save_tb: true

seed: 1


# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp