defaults:
    - agent: sac

env: platoon_exp

# "shared" or "individual"
multi_agent_mode: individual
equalize_agents: true

# "train" or "eval"
mode: train
render: false

load_checkpoint: false
save_checkpoint: true
checkpoint_frequency: 50000

run_directory: downloads/2024-02-14_09-53/09-53
checkpoint: cp_550244

num_train_steps: 12000
replay_buffer_capacity: 50000 #${num_train_steps}

num_seed_steps: 600

eval_frequency: 4000
num_eval_episodes: 6

fed_enabled: false
fed_and_update: false
fed_actor: true
fed_critic: true
fed_target: true
fed_alpha: true
fed_frequency: 6
fed_pre_weight: 0.33
fed_post_weight: 0.33
fed_first_post_weight: 0.5
fed_last_pre_weight: 0.5


# "cuda" or "cpu"
device: cuda

# logger
log_frequency: 600
log_save_tb: true

overall_seed: 1
initial_actions_seed: 1


# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp
