defaults:
    - agent: sac

env: platoon_exp

# "shared" or "individual"
multi_agent_mode: shared

# "train" or "eval"
mode: train
render: false

load_checkpoint: false
save_checkpoint: true
checkpoint_frequency: 1000

run_directory: 2024-01-15/23-07
checkpoint: cp_1833

num_train_steps: 2000
replay_buffer_capacity: 50000 #${num_train_steps}

num_seed_steps: 600

eval_frequency: 1000
num_eval_episodes: 2

# "cuda" or "cpu"
device: cpu

# logger
log_frequency: 600
log_save_tb: true

seed: 1


# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp
