defaults:
    - agent: sac

env: multi_lane_highway_5V

load_checkpoint: true
save_checkpoint: true

checkpoint_dir: 2023-12-07/14-35
checkpoint_name: checkpoint-2400.pt

experiment: test_exp

num_train_steps: 4800
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 3000

eval_frequency: 100000
num_eval_episodes: 1

device: cuda

# logger
log_frequency: 600
log_save_tb: true

# video recorder
save_video: false


seed: 1


# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp